import { test } from 'node:test';
import assert from 'node:assert/strict';
import { loadProducts } from '../lib/products.js';
import { renderHead, renderBodyOpen, renderFooter, renderGalleryModal, renderSpecsModal, renderScripts } from '../templates/partials.js';

const p = loadProducts('data/products.sample.json')[0];

test('head has title, stylesheets, no leftover placeholder', () => {
  const h = renderHead(p);
  assert.match(h, /<title>Sample Bench \| York Barbell<\/title>/);
  assert.match(h, /href="css\/tokens\.css\?v=[a-f0-9]+"/);
  assert.match(h, /href="css\/pages\.css\?v=[a-f0-9]+"/);
  assert.doesNotMatch(h, /\{\{/);
});

test('head always emits the generated-do-not-edit banner', () => {
  const h = renderHead(p);
  assert.match(h, /GENERATED by tools\/build-products\.mjs from data\/products\.json — do not edit by hand/);
});

test('head emits the drafted-copy banner only when copySource is drafted-by-claude', () => {
  const notDrafted = renderHead(p);
  assert.doesNotMatch(notDrafted, /COPY DRAFTED BY CLAUDE/);

  const drafted = renderHead({ ...p, copySource: 'drafted-by-claude' });
  assert.match(drafted, /COPY DRAFTED BY CLAUDE — pending client approval/);
});

test('body open carries the template-specific class and the mega menu', () => {
  const b = renderBodyOpen(p);
  assert.match(b, /<body class="pdp-page pdp-single">/);
  assert.match(b, /announcement-bar/);
  assert.match(b, /class="chrome-top"/);
});

test('body open maps generic and package templates to the right body class', () => {
  const generic = renderBodyOpen({ ...p, template: 'generic' });
  assert.match(generic, /<body class="pdp-page pdp-generic">/);

  const pkg = renderBodyOpen({ ...p, template: 'package' });
  assert.match(pkg, /<body class="pdp-page pdp-package">/);
});

test('gallery modal emits one slide per image (3 for the fixture)', () => {
  const g = renderGalleryModal(p);
  assert.equal((g.match(/data-carousel-slide/g) || []).length, 3);
  assert.equal((g.match(/data-carousel-dot/g) || []).length, 3);
});

test('specs modal lists each spec', () => {
  const s = renderSpecsModal(p);
  assert.match(s, /Weight 38 lb/);
  assert.match(s, /Dimensions 44 × 17 × 9/);
});

test('footer + scripts close the document', () => {
  assert.match(renderFooter(), /site-footer/);
  assert.match(renderScripts(), /js\/chrome\.js/);
  assert.match(renderScripts(), /<\/html>/);
});
